3dcap-md-gen: Window Class Reference
Window Class Reference
GUI.
Public Member Functions
def __init__ (self)
def initUI (self)
def close_window (self)
def show_file_browser (self)
def return_unit (self)
def first_browser (self)
def request_withUri (self)
def startMetadata (self)
Public Attributes
filepath
unit_mm
unit_cm
unit_m
unit_project
uri
filename
Detailed Description
GUI.
Constructor & Destructor Documentation
__init__()
def __init__ (self)
         def __init__(self):
                 super().__init__()
                 self.initUI()
References Window.initUI().
Member Function Documentation
close_window()
def close_window (self)
         def close_window(self):
                 print ("6")
                 root.destroy()
Referenced by Window.startMetadata().
first_browser()
def first_browser (self)
         def first_browser(self):
                 file = self.show_file_browser()
                 self.filepath.set(file)
References Window.filepath, and Window.show_file_browser().
initUI()
def initUI (self)
         def initUI(self):
                 self.master.title("Metadaten Agisoft Metashape")
                 self.master.rowconfigure( 0, weight = 1 )
                 self.master.columnconfigure( 0, weight = 10)
                 self.grid( sticky = W+E+N+S )
                 # Variablen
                 self.filepath = tkinter.StringVar()
                 self.unit_mm = tkinter.IntVar()
                 self.unit_cm = tkinter.IntVar()
                 self.unit_m = tkinter.IntVar()
                 self.unit_project = tkinter.IntVar()
                 self.uri = tkinter.BooleanVar()
                 filegroup = LabelFrame(self, text = "Agisoft file")
                 filegroup.grid(row = 0, column = 0, sticky = W, padx=5, pady=5 )
                 browseButton = Button(filegroup, text = 'Browse', command = self.first_browser)
                 browseButton.grid(row = 1, column=0, sticky = W+E+N+S, padx=5, pady=5 )
                 filepathText = Entry(filegroup, textvariable = self.filepath, width=150)
                 filepathText.grid(row = 1, column = 1, columnspan=5, sticky = W+E+N+S , padx=5, pady=5)
                 lbl = Label(filegroup,text="Select one unit:")
                 lbl.grid(row = 2, column=0, sticky = W)
                 checkbutton_mm = Checkbutton(filegroup, text="millimetre", variable=self.unit_mm)
                 checkbutton_mm.grid(row = 2, column=1, sticky = W+E+N+S, padx=5, pady=5 )
                 checkbutton_m = Checkbutton(filegroup, text="metre", variable=self.unit_m)
                 checkbutton_m.grid(row = 2, column=3, sticky = W+E+N+S, padx=5, pady=5 )
                 lbl_2 = Label(filegroup,text="Output with URI only:")
                 lbl_2.grid(row = 3, column=0, sticky = W)
                 checkbutton_uri = Checkbutton(filegroup, variable=self.uri)
                 checkbutton_uri.grid(row = 3, column=1, sticky = W, padx=5, pady=5 )
                 checkbutton_project = Checkbutton(filegroup, text="project unit", variable=self.unit_project)
                 checkbutton_project.grid(row = 2, column=5, sticky = W+E+N+S, padx=5, pady=5 )
                 browseButton = Button(filegroup, text = 'Start', command = self.startMetadata)
                 browseButton.grid(row = 4, column=0, sticky = W, padx=5, pady=5 )
Referenced by Window.__init__().
request_withUri()
def request_withUri (self)
         def request_withUri(self):
                 print(':...................')
                 print(self.uri)
                 #print(includeonlypropswithuri)
                 if self.uri.get() == True:
                         includeonlypropswithuri= True
                 else:
                         includeonlypropswithuri=False
                 print(includeonlypropswithuri)
                 return includeonlypropswithuri
References Window.uri.
Referenced by Window.startMetadata().
return_unit()
def return_unit (self)
         def return_unit (self):
                 if self.unit_mm.get() == 1:
                         unit = 'unit_mm'
                         print ("millimetre units")
                         print (unit)
                 elif self.unit_m.get() == 1:
                         unit = 'unit_m'
                         print ("metre units")
                         print (unit)
                 elif self.unit_project.get() == 1:
                         unit = 'unit_project'
                         print ("project units")
                         print (unit)
                 else:
                         unit = None
                         print ("... units")
                         print (unit)
                 return unit
References Window.unit_m, Window.unit_mm, and Window.unit_project.
Referenced by Window.startMetadata().
show_file_browser()
def show_file_browser (self)
         def show_file_browser(self):
                 filetypes = (('text files', '*.psx'),('All files', '*.*'))
                 self.filename = filedialog.askopenfilename(filetypes=filetypes)
                 print ("... file open ... " + self.filename)
                 return self.filename
Referenced by Window.first_browser().
startMetadata()
def startMetadata (self)
         def startMetadata (self):
                 unit = self.return_unit()
                 includeonlypropswithuri= self.request_withUri()
                 print ("... projekt wird zur nächsten Methode übergeben und gestartet")
                 exportMeta(self.filename , unit, includeonlypropswithuri)
                 print ("... close GUI")
                 self.close_window()
References Window.close_window(), agisoft-metashape_3dcap-metadata.exportMeta(), Window.filename, Window.request_withUri(), and Window.return_unit().
Member Data Documentation
filename
filename
Referenced by Window.startMetadata().
filepath
filepath
Referenced by Window.first_browser().
unit_cm
unit_cm
unit_m
unit_m
Referenced by Window.return_unit().
unit_mm
unit_mm
Referenced by Window.return_unit().
unit_project
unit_project
Referenced by Window.return_unit().
uri
uri
Referenced by Window.request_withUri().